import type { FastifyInstance, FastifyRequest, FastifyReply } from 'fastify';
import secureSession from '@fastify/secure-session';
import type { Environment } from '../../config/environment.js';
import { authEnabled } from '../../config/environment.js';
import { UserRepository, type UserRow } from '../../services/UserRepository.js';

declare module 'fastify' {
  interface FastifyRequest {
    user: UserRow | null;
  }
}

export async function requireUser(req: FastifyRequest, reply: FastifyReply): Promise<void> {
  if (!req.user) {
    return reply.status(401).send({ error: 'Authentication required' });
  }
}

export async function requireAdmin(req: FastifyRequest, reply: FastifyReply): Promise<void> {
  if (!req.user) {
    return reply.status(401).send({ error: 'Authentication required' });
  }
  if (req.user.role !== 'admin') {
    return reply.status(403).send({ error: 'Admin only' });
  }
}

/**
 * Register the session store and a preHandler that loads request.user.
 *
 * Open mode (AUTH_ENABLED=false):
 *   Attaches the bootstrap-admin user (from DB if it exists, otherwise a
 *   synthetic record) so existing open-dashboard behaviour is preserved.
 *
 * Auth mode (AUTH_ENABLED=true):
 *   Registers @fastify/secure-session with a 32-byte key derived from
 *   SESSION_SECRET via padEnd/slice. In production prefer a proper
 *   base64/hex 32-byte key generated by `npx @fastify/secure-session`.
 *   Then adds a preHandler that resolves request.user from the session's
 *   'userId' value.
 */
export async function registerAuth(app: FastifyInstance, config: Environment): Promise<void> {
  // Decorate every request with user = null as the default.
  app.decorateRequest('user', null);

  if (!authEnabled(config)) {
    // Open mode: always attach the bootstrap admin so admin routes work.
    app.addHook('preHandler', async (req) => {
      const fromDb = UserRepository.findById('bootstrap-admin');
      req.user = fromDb ?? ({
        id: 'bootstrap-admin',
        email: '',
        role: 'admin',
        entraObjectId: null,
        name: 'Bootstrap Admin',
      } as UserRow);
    });
    return;
  }

  // Derive a 32-byte Buffer from SESSION_SECRET (padEnd/slice is a pragmatic
  // derivation for dev/staging; for production generate a proper key with
  // `npx @fastify/secure-session > secret-key` and load it from a file).
  const rawSecret = config.SESSION_SECRET ?? '';
  const key = Buffer.from(rawSecret.padEnd(32, '0').slice(0, 32));

  await app.register(secureSession, {
    key,
    cookieName: 'agenthub_session',
    cookie: {
      path: '/',
      httpOnly: true,
      sameSite: 'lax',
      secure: true,
    },
  });

  app.addHook('preHandler', async (req) => {
    const uid = req.session.get('userId') as string | undefined;
    req.user = uid ? (UserRepository.findById(uid) ?? null) : null;
  });
}
